os: linux
language: php

dist: xenial

addons:
  apt:
    packages:
      - beanstalkd
      - gdb
      - re2c
      - libpng12-dev
      - libqrencode-dev
      - libzbar-dev
      - imagemagick
      - libmagick++-dev
      - libmagickcore-dev
      - libmagickwand-dev
      - pkg-config
      - libssl-dev
      - libsasl2-dev
      - libleveldb-dev

php:
  - 7.4
  - nightly

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly

git:
  depth: 1

cache:
  apt: true
  ccache: true
  timeout: 691200
  directories:
    - .temp
    #- vendor
    - $HOME/.ccache
    - $HOME/.composer/cache

services:
  - mysql
  - mongodb
  - memcached
  - redis
  - postgresql

env:
  global:
    - TEST_DB_MONGO_HOST="127.0.0.1"
    - TEST_DB_MONGO_PORT="27017"
    - TEST_DB_MONGO_USER="admin"
    - TEST_DB_MONGO_PASSWD=""
    - TEST_DB_MONGO_NAME="phalcon_test"
    #- ENABLE_MAINTAINER_ZTS=1 ENABLE_DEBUG=1 USE_ZEND_ALLOC=0
    - CC="ccache gcc"

before_install:
  - sudo apt-get install -y fonts-urw-base35 || true
  - sudo apt-get install -y fonts-freefont-ttf || true
  - sudo apt-get install -y libfreetype6-dev || true
  - export PATH=$PATH:~/bin;
  - export LD_LIBRARY_PATH=/usr/lib:/usr/lib64:/lib:/lib64:/usr/local/lib:/usr/local/lib64:$LD_LIBRARY_PATH
  - composer self-update -q
  - travis_retry composer --prefer-source install
  - ./unit-tests/ci/install_prereqs.sh
  - ./unit-tests/ci/setup_dbs.sh

before_script:
  - (cd ext; export CFLAGS="-g -O0 -std=gnu90 -Wall -Werror -Wno-error=uninitialized"; phpize && ./configure --enable-chart=yes --enable-qrcode=yes --enable-process=yes --enable-intrusive=yes --enable-storage-bloomfilter=yes --enable-storage-datrie=yes && make --silent -j4 > /dev/null && make --silent install && phpenv config-add ../unit-tests/ci/20-phalcon.ini)
  - ulimit -c unlimited -S || true
  - echo '/tmp/core_%e.%p' | sudo tee /proc/sys/kernel/core_pattern &> /dev/null

script:
  - vendor/bin/phpunit --stderr --debug unit-tests/

after_failure:
  - bash unit-tests/ci/after_failure.sh

notifications:
  email:
    - dreamsxin@qq.com
